[package]
name = "dedalus"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.38", features = ["serialize"] }
bzip2 = { version = "0.6" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
csv = { version = "1.4" }
regex = { version = "1.12.2" }
anyhow = { version = "1.0" }
indicatif = { version = "0.18.3" }
clap = { version = "4.5.53", features = ["derive"] }